media:
  input: public
  output: /

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    include:
      - "**/*.md"
      - "**/*.mdx"
    view:
      fields: [title, draft, pubDate]

    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: pubDate, label: Publish Date, type: date, required: true }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: image, label: Cover Image (URL), type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Body, type: rich-text }
