media:
  input: public
  output: /

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    include:
      - "**/*.md"
      - "**/*.mdx"

    view:
      fields: [title, draft, publishDate]

    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: string

      - name: publishDate
        label: Publish Date
        type: date
        required: true
        options:
          format: "yyyy-MM-dd"

      - name: tags
        label: Tags
        type: string
        list: true

      - name: image
        label: Cover Image (URL)
        type: string

      - name: draft
        label: Draft
        type: boolean
        default: false

      - name: body
        label: Body
        type: markdown

  - name: docs
    label: Docs
    type: collection
    path: src/content/docs
    include:
      - "**/*.md"
      - "**/*.mdx"

    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: string

      - name: body
        label: Body
        type: markdown
