version: 1

collections:
  - name: blog
    label: Blog Posts
    path: src/content/blog
    type: markdown
    include:
      - "**/*.md"
      - "**/*.mdx"
    slug: "{{path}}"

    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: string

      - name: pubDate
        label: Publish Date
        type: date
        required: true

      - name: tags
        label: Tags
        type: list
        item:
          type: string

      - name: image
        label: Cover Image (Cloudinary URL)
        type: string

      - name: draft
        label: Draft
        type: boolean
        default: false

      - name: body
        label: Content
        type: markdown
